# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bitstream_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import chip_config_pb2 as chip__config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bitstream_config.proto',
  package='neurosim',
  syntax='proto2',
  serialized_pb=_b('\n\x16\x62itstream_config.proto\x12\x08neurosim\x1a\x11\x63hip_config.proto\"\xa5\x06\n\x13\x42itstreamCoreConfig\x12\x0f\n\x07\x63ore_id\x18\x01 \x02(\x05\x12\x11\n\tnum_axons\x18\x02 \x02(\x05\x12\x13\n\x0bnum_neurons\x18\x03 \x02(\x05\x12\x17\n\x0blayer_index\x18\x08 \x01(\x05:\x02-1\x12X\n\x17\x64igital_crosspoint_data\x18\x05 \x01(\x0b\x32\x35.neurosim.BitstreamCoreConfig.DigitalCrosspointConfigH\x00\x12R\n\x14rram_crosspoint_data\x18\x06 \x01(\x0b\x32\x32.neurosim.BitstreamCoreConfig.RRAMCrosspointConfigH\x00\x12\\\n\x19\x66loattype_crosspoint_data\x18\x11 \x01(\x0b\x32\x37.neurosim.BitstreamCoreConfig.FloatTypeCrosspointConfigH\x00\x12;\n\x07neurons\x18\x07 \x03(\x0b\x32*.neurosim.BitstreamCoreConfig.NeuronConfig\x1a)\n\x17\x44igitalCrosspointConfig\x12\x0e\n\x06values\x18\x01 \x03(\x05\x1a+\n\x19\x46loatTypeCrosspointConfig\x12\x0e\n\x06values\x18\x01 \x03(\x02\x1aH\n\x14RRAMCrosspointConfig\x12\x17\n\x0fpos_resistances\x18\x01 \x03(\x02\x12\x17\n\x0fneg_resistances\x18\x02 \x03(\x02\x1a>\n\x10\x43onnectionConfig\x12\x14\n\x0c\x64\x65st_core_id\x18\x01 \x02(\x05\x12\x14\n\x0c\x64\x65st_axon_id\x18\x02 \x02(\x05\x1a~\n\x0cNeuronConfig\x12\x43\n\x0b\x63onnections\x18\x01 \x03(\x0b\x32..neurosim.BitstreamCoreConfig.ConnectionConfig\x12)\n\x06neuron\x18\x02 \x02(\x0b\x32\x19.neurosim.LIFNeuronConfigB\x11\n\x0f\x63rosspoint_data\"\\\n\x0f\x42itstreamConfig\x12\x16\n\x0enum_used_cores\x18\x01 \x02(\x05\x12\x31\n\nbitstreams\x18\x02 \x03(\x0b\x32\x1d.neurosim.BitstreamCoreConfig')
  ,
  dependencies=[chip__config__pb2.DESCRIPTOR,])




_BITSTREAMCORECONFIG_DIGITALCROSSPOINTCONFIG = _descriptor.Descriptor(
  name='DigitalCrosspointConfig',
  full_name='neurosim.BitstreamCoreConfig.DigitalCrosspointConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='neurosim.BitstreamCoreConfig.DigitalCrosspointConfig.values', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=490,
  serialized_end=531,
)

_BITSTREAMCORECONFIG_FLOATTYPECROSSPOINTCONFIG = _descriptor.Descriptor(
  name='FloatTypeCrosspointConfig',
  full_name='neurosim.BitstreamCoreConfig.FloatTypeCrosspointConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='neurosim.BitstreamCoreConfig.FloatTypeCrosspointConfig.values', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=533,
  serialized_end=576,
)

_BITSTREAMCORECONFIG_RRAMCROSSPOINTCONFIG = _descriptor.Descriptor(
  name='RRAMCrosspointConfig',
  full_name='neurosim.BitstreamCoreConfig.RRAMCrosspointConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos_resistances', full_name='neurosim.BitstreamCoreConfig.RRAMCrosspointConfig.pos_resistances', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='neg_resistances', full_name='neurosim.BitstreamCoreConfig.RRAMCrosspointConfig.neg_resistances', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=578,
  serialized_end=650,
)

_BITSTREAMCORECONFIG_CONNECTIONCONFIG = _descriptor.Descriptor(
  name='ConnectionConfig',
  full_name='neurosim.BitstreamCoreConfig.ConnectionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dest_core_id', full_name='neurosim.BitstreamCoreConfig.ConnectionConfig.dest_core_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dest_axon_id', full_name='neurosim.BitstreamCoreConfig.ConnectionConfig.dest_axon_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=652,
  serialized_end=714,
)

_BITSTREAMCORECONFIG_NEURONCONFIG = _descriptor.Descriptor(
  name='NeuronConfig',
  full_name='neurosim.BitstreamCoreConfig.NeuronConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='connections', full_name='neurosim.BitstreamCoreConfig.NeuronConfig.connections', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='neuron', full_name='neurosim.BitstreamCoreConfig.NeuronConfig.neuron', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=716,
  serialized_end=842,
)

_BITSTREAMCORECONFIG = _descriptor.Descriptor(
  name='BitstreamCoreConfig',
  full_name='neurosim.BitstreamCoreConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='core_id', full_name='neurosim.BitstreamCoreConfig.core_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_axons', full_name='neurosim.BitstreamCoreConfig.num_axons', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_neurons', full_name='neurosim.BitstreamCoreConfig.num_neurons', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='layer_index', full_name='neurosim.BitstreamCoreConfig.layer_index', index=3,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='digital_crosspoint_data', full_name='neurosim.BitstreamCoreConfig.digital_crosspoint_data', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rram_crosspoint_data', full_name='neurosim.BitstreamCoreConfig.rram_crosspoint_data', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='floattype_crosspoint_data', full_name='neurosim.BitstreamCoreConfig.floattype_crosspoint_data', index=6,
      number=17, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='neurons', full_name='neurosim.BitstreamCoreConfig.neurons', index=7,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_BITSTREAMCORECONFIG_DIGITALCROSSPOINTCONFIG, _BITSTREAMCORECONFIG_FLOATTYPECROSSPOINTCONFIG, _BITSTREAMCORECONFIG_RRAMCROSSPOINTCONFIG, _BITSTREAMCORECONFIG_CONNECTIONCONFIG, _BITSTREAMCORECONFIG_NEURONCONFIG, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='crosspoint_data', full_name='neurosim.BitstreamCoreConfig.crosspoint_data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=56,
  serialized_end=861,
)


_BITSTREAMCONFIG = _descriptor.Descriptor(
  name='BitstreamConfig',
  full_name='neurosim.BitstreamConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_used_cores', full_name='neurosim.BitstreamConfig.num_used_cores', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bitstreams', full_name='neurosim.BitstreamConfig.bitstreams', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=863,
  serialized_end=955,
)

_BITSTREAMCORECONFIG_DIGITALCROSSPOINTCONFIG.containing_type = _BITSTREAMCORECONFIG
_BITSTREAMCORECONFIG_FLOATTYPECROSSPOINTCONFIG.containing_type = _BITSTREAMCORECONFIG
_BITSTREAMCORECONFIG_RRAMCROSSPOINTCONFIG.containing_type = _BITSTREAMCORECONFIG
_BITSTREAMCORECONFIG_CONNECTIONCONFIG.containing_type = _BITSTREAMCORECONFIG
_BITSTREAMCORECONFIG_NEURONCONFIG.fields_by_name['connections'].message_type = _BITSTREAMCORECONFIG_CONNECTIONCONFIG
_BITSTREAMCORECONFIG_NEURONCONFIG.fields_by_name['neuron'].message_type = chip__config__pb2._LIFNEURONCONFIG
_BITSTREAMCORECONFIG_NEURONCONFIG.containing_type = _BITSTREAMCORECONFIG
_BITSTREAMCORECONFIG.fields_by_name['digital_crosspoint_data'].message_type = _BITSTREAMCORECONFIG_DIGITALCROSSPOINTCONFIG
_BITSTREAMCORECONFIG.fields_by_name['rram_crosspoint_data'].message_type = _BITSTREAMCORECONFIG_RRAMCROSSPOINTCONFIG
_BITSTREAMCORECONFIG.fields_by_name['floattype_crosspoint_data'].message_type = _BITSTREAMCORECONFIG_FLOATTYPECROSSPOINTCONFIG
_BITSTREAMCORECONFIG.fields_by_name['neurons'].message_type = _BITSTREAMCORECONFIG_NEURONCONFIG
_BITSTREAMCORECONFIG.oneofs_by_name['crosspoint_data'].fields.append(
  _BITSTREAMCORECONFIG.fields_by_name['digital_crosspoint_data'])
_BITSTREAMCORECONFIG.fields_by_name['digital_crosspoint_data'].containing_oneof = _BITSTREAMCORECONFIG.oneofs_by_name['crosspoint_data']
_BITSTREAMCORECONFIG.oneofs_by_name['crosspoint_data'].fields.append(
  _BITSTREAMCORECONFIG.fields_by_name['rram_crosspoint_data'])
_BITSTREAMCORECONFIG.fields_by_name['rram_crosspoint_data'].containing_oneof = _BITSTREAMCORECONFIG.oneofs_by_name['crosspoint_data']
_BITSTREAMCORECONFIG.oneofs_by_name['crosspoint_data'].fields.append(
  _BITSTREAMCORECONFIG.fields_by_name['floattype_crosspoint_data'])
_BITSTREAMCORECONFIG.fields_by_name['floattype_crosspoint_data'].containing_oneof = _BITSTREAMCORECONFIG.oneofs_by_name['crosspoint_data']
_BITSTREAMCONFIG.fields_by_name['bitstreams'].message_type = _BITSTREAMCORECONFIG
DESCRIPTOR.message_types_by_name['BitstreamCoreConfig'] = _BITSTREAMCORECONFIG
DESCRIPTOR.message_types_by_name['BitstreamConfig'] = _BITSTREAMCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BitstreamCoreConfig = _reflection.GeneratedProtocolMessageType('BitstreamCoreConfig', (_message.Message,), dict(

  DigitalCrosspointConfig = _reflection.GeneratedProtocolMessageType('DigitalCrosspointConfig', (_message.Message,), dict(
    DESCRIPTOR = _BITSTREAMCORECONFIG_DIGITALCROSSPOINTCONFIG,
    __module__ = 'bitstream_config_pb2'
    # @@protoc_insertion_point(class_scope:neurosim.BitstreamCoreConfig.DigitalCrosspointConfig)
    ))
  ,

  FloatTypeCrosspointConfig = _reflection.GeneratedProtocolMessageType('FloatTypeCrosspointConfig', (_message.Message,), dict(
    DESCRIPTOR = _BITSTREAMCORECONFIG_FLOATTYPECROSSPOINTCONFIG,
    __module__ = 'bitstream_config_pb2'
    # @@protoc_insertion_point(class_scope:neurosim.BitstreamCoreConfig.FloatTypeCrosspointConfig)
    ))
  ,

  RRAMCrosspointConfig = _reflection.GeneratedProtocolMessageType('RRAMCrosspointConfig', (_message.Message,), dict(
    DESCRIPTOR = _BITSTREAMCORECONFIG_RRAMCROSSPOINTCONFIG,
    __module__ = 'bitstream_config_pb2'
    # @@protoc_insertion_point(class_scope:neurosim.BitstreamCoreConfig.RRAMCrosspointConfig)
    ))
  ,

  ConnectionConfig = _reflection.GeneratedProtocolMessageType('ConnectionConfig', (_message.Message,), dict(
    DESCRIPTOR = _BITSTREAMCORECONFIG_CONNECTIONCONFIG,
    __module__ = 'bitstream_config_pb2'
    # @@protoc_insertion_point(class_scope:neurosim.BitstreamCoreConfig.ConnectionConfig)
    ))
  ,

  NeuronConfig = _reflection.GeneratedProtocolMessageType('NeuronConfig', (_message.Message,), dict(
    DESCRIPTOR = _BITSTREAMCORECONFIG_NEURONCONFIG,
    __module__ = 'bitstream_config_pb2'
    # @@protoc_insertion_point(class_scope:neurosim.BitstreamCoreConfig.NeuronConfig)
    ))
  ,
  DESCRIPTOR = _BITSTREAMCORECONFIG,
  __module__ = 'bitstream_config_pb2'
  # @@protoc_insertion_point(class_scope:neurosim.BitstreamCoreConfig)
  ))
_sym_db.RegisterMessage(BitstreamCoreConfig)
_sym_db.RegisterMessage(BitstreamCoreConfig.DigitalCrosspointConfig)
_sym_db.RegisterMessage(BitstreamCoreConfig.FloatTypeCrosspointConfig)
_sym_db.RegisterMessage(BitstreamCoreConfig.RRAMCrosspointConfig)
_sym_db.RegisterMessage(BitstreamCoreConfig.ConnectionConfig)
_sym_db.RegisterMessage(BitstreamCoreConfig.NeuronConfig)

BitstreamConfig = _reflection.GeneratedProtocolMessageType('BitstreamConfig', (_message.Message,), dict(
  DESCRIPTOR = _BITSTREAMCONFIG,
  __module__ = 'bitstream_config_pb2'
  # @@protoc_insertion_point(class_scope:neurosim.BitstreamConfig)
  ))
_sym_db.RegisterMessage(BitstreamConfig)


# @@protoc_insertion_point(module_scope)
