# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: power_model_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='power_model_config.proto',
  package='neurosim',
  syntax='proto2',
  serialized_pb=_b('\n\x18power_model_config.proto\x12\x08neurosim\"\xdc\x06\n\x10PowerModelConfig\x12\x1c\n\x11\x62\x61seline_per_core\x18\x01 \x02(\x02:\x01\x30\x12\x1e\n\x13\x62\x61seline_per_router\x18\x0c \x02(\x02:\x01\x30\x12!\n\x16\x63oef_synapse_stimulate\x18\x02 \x02(\x02:\x01\x30\x12\x1f\n\x14\x63oef_neuron_activate\x18\x03 \x02(\x02:\x01\x30\x12\x1d\n\x12\x63oef_net_injection\x18\x04 \x02(\x02:\x01\x30\x12\x1c\n\x11\x63oef_net_ejection\x18\x05 \x02(\x02:\x01\x30\x12\x1b\n\x10\x63oef_router_push\x18\x06 \x02(\x02:\x01\x30\x12\x1c\n\x11\x63oef_router_popup\x18\x07 \x02(\x02:\x01\x30\x12\x1c\n\x11\x63oef_router_setup\x18\x08 \x02(\x02:\x01\x30\x12\x1d\n\x12\x63oef_router_switch\x18\t \x02(\x02:\x01\x30\x12\x1f\n\x14\x63oef_router_transfer\x18\n \x02(\x02:\x01\x30\x12 \n\x11\x63oef_core_synapse\x18\r \x02(\x02:\x05\x31\x65-07\x12\x1f\n\x10\x63oef_neuron_tia1\x18\x1a \x02(\x02:\x05\x32\x65-08\x12!\n\x10\x63oef_neuron_tia2\x18\x0e \x02(\x02:\x07\x32.4e-16\x12 \n\x0f\x63oef_neuron_adc\x18\x0f \x02(\x02:\x07\x31.2e-14\x12!\n\x10\x63oef_neuron_reg1\x18\x10 \x02(\x02:\x07\x31.4e-17\x12#\n\x10\x63oef_neuron_reg2\x18\x11 \x02(\x02:\t7.452e-15\x12#\n\x11\x63oef_neuron_arith\x18\x12 \x02(\x02:\x08\x36.71e-15\x12\"\n\x10\x63oef_router_sta1\x18\x13 \x02(\x02:\x08\x31.01e-13\x12\x1f\n\x10\x63oef_router_sta2\x18\x14 \x02(\x02:\x05\x31\x65-13\x12#\n\x10\x63oef_router_sta3\x18\x15 \x02(\x02:\t4.747e-05\x12&\n\x13\x63oef_router_dynamic\x18\x16 \x02(\x02:\t2.484e-15\x12 \n\x0e\x63oef_router_sw\x18\x17 \x02(\x02:\x08\x36.21e-16\x12#\n\x10\x63oef_router_ctrl\x18\x18 \x02(\x02:\t4.968e-14\x12\"\n\x10\x63oef_router_link\x18\x19 \x02(\x02:\x08\x34.68e-17')
)




_POWERMODELCONFIG = _descriptor.Descriptor(
  name='PowerModelConfig',
  full_name='neurosim.PowerModelConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='baseline_per_core', full_name='neurosim.PowerModelConfig.baseline_per_core', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='baseline_per_router', full_name='neurosim.PowerModelConfig.baseline_per_router', index=1,
      number=12, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_synapse_stimulate', full_name='neurosim.PowerModelConfig.coef_synapse_stimulate', index=2,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_neuron_activate', full_name='neurosim.PowerModelConfig.coef_neuron_activate', index=3,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_net_injection', full_name='neurosim.PowerModelConfig.coef_net_injection', index=4,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_net_ejection', full_name='neurosim.PowerModelConfig.coef_net_ejection', index=5,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_router_push', full_name='neurosim.PowerModelConfig.coef_router_push', index=6,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_router_popup', full_name='neurosim.PowerModelConfig.coef_router_popup', index=7,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_router_setup', full_name='neurosim.PowerModelConfig.coef_router_setup', index=8,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_router_switch', full_name='neurosim.PowerModelConfig.coef_router_switch', index=9,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_router_transfer', full_name='neurosim.PowerModelConfig.coef_router_transfer', index=10,
      number=10, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_core_synapse', full_name='neurosim.PowerModelConfig.coef_core_synapse', index=11,
      number=13, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(1e-07),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_neuron_tia1', full_name='neurosim.PowerModelConfig.coef_neuron_tia1', index=12,
      number=26, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(2e-08),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_neuron_tia2', full_name='neurosim.PowerModelConfig.coef_neuron_tia2', index=13,
      number=14, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(2.4e-16),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_neuron_adc', full_name='neurosim.PowerModelConfig.coef_neuron_adc', index=14,
      number=15, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(1.2e-14),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_neuron_reg1', full_name='neurosim.PowerModelConfig.coef_neuron_reg1', index=15,
      number=16, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(1.4e-17),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_neuron_reg2', full_name='neurosim.PowerModelConfig.coef_neuron_reg2', index=16,
      number=17, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(7.452e-15),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_neuron_arith', full_name='neurosim.PowerModelConfig.coef_neuron_arith', index=17,
      number=18, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(6.71e-15),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_router_sta1', full_name='neurosim.PowerModelConfig.coef_router_sta1', index=18,
      number=19, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(1.01e-13),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_router_sta2', full_name='neurosim.PowerModelConfig.coef_router_sta2', index=19,
      number=20, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(1e-13),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_router_sta3', full_name='neurosim.PowerModelConfig.coef_router_sta3', index=20,
      number=21, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(4.747e-05),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_router_dynamic', full_name='neurosim.PowerModelConfig.coef_router_dynamic', index=21,
      number=22, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(2.484e-15),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_router_sw', full_name='neurosim.PowerModelConfig.coef_router_sw', index=22,
      number=23, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(6.21e-16),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_router_ctrl', full_name='neurosim.PowerModelConfig.coef_router_ctrl', index=23,
      number=24, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(4.968e-14),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coef_router_link', full_name='neurosim.PowerModelConfig.coef_router_link', index=24,
      number=25, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(4.68e-17),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=899,
)

DESCRIPTOR.message_types_by_name['PowerModelConfig'] = _POWERMODELCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PowerModelConfig = _reflection.GeneratedProtocolMessageType('PowerModelConfig', (_message.Message,), dict(
  DESCRIPTOR = _POWERMODELCONFIG,
  __module__ = 'power_model_config_pb2'
  # @@protoc_insertion_point(class_scope:neurosim.PowerModelConfig)
  ))
_sym_db.RegisterMessage(PowerModelConfig)


# @@protoc_insertion_point(module_scope)
