# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rram_noise_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rram_noise_config.proto',
  package='neurosim',
  syntax='proto2',
  serialized_pb=_b('\n\x17rram_noise_config.proto\x12\x08neurosim\"\xae\x01\n\x0fRRAMNoiseConfig\x12\x18\n\x08t_sample\x18\x01 \x02(\x02:\x06\x30.0005\x12\x12\n\x04t_on\x18\x02 \x02(\x02:\x04\x30.02\x12\x13\n\x05t_off\x18\x03 \x02(\x02:\x04\x30.05\x12\x16\n\x08material\x18\x04 \x02(\t:\x04hfo2\x12\x1d\n\x12write_verify_iters\x18\x05 \x02(\x05:\x01\x31\x12!\n\x16write_verify_tolerance\x18\x06 \x02(\x02:\x01\x30')
)




_RRAMNOISECONFIG = _descriptor.Descriptor(
  name='RRAMNoiseConfig',
  full_name='neurosim.RRAMNoiseConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='t_sample', full_name='neurosim.RRAMNoiseConfig.t_sample', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0.0005),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='t_on', full_name='neurosim.RRAMNoiseConfig.t_on', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0.02),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='t_off', full_name='neurosim.RRAMNoiseConfig.t_off', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0.05),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='material', full_name='neurosim.RRAMNoiseConfig.material', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("hfo2").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='write_verify_iters', full_name='neurosim.RRAMNoiseConfig.write_verify_iters', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='write_verify_tolerance', full_name='neurosim.RRAMNoiseConfig.write_verify_tolerance', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=212,
)

DESCRIPTOR.message_types_by_name['RRAMNoiseConfig'] = _RRAMNOISECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RRAMNoiseConfig = _reflection.GeneratedProtocolMessageType('RRAMNoiseConfig', (_message.Message,), dict(
  DESCRIPTOR = _RRAMNOISECONFIG,
  __module__ = 'rram_noise_config_pb2'
  # @@protoc_insertion_point(class_scope:neurosim.RRAMNoiseConfig)
  ))
_sym_db.RegisterMessage(RRAMNoiseConfig)


# @@protoc_insertion_point(module_scope)
