# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simulation_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simulation_config.proto',
  package='neurosim',
  syntax='proto2',
  serialized_pb=_b('\n\x17simulation_config.proto\x12\x08neurosim\"\xf1\x06\n\x10SimulationConfig\x12\x19\n\x0enum_total_secs\x18\x01 \x02(\x02:\x01\x31\x12\x1e\n\x11\x66requency_in_core\x18\x02 \x02(\x05:\x03\x32\x30\x30\x12 \n\x11\x66requency_in_comm\x18\x03 \x02(\x05:\x05\x32\x30\x30\x30\x30\x12\x15\n\rspike_sources\x18\x04 \x02(\t\x12\x1a\n\x12\x62itstream_filename\x18\x05 \x02(\t\x12.\n\x14\x63hip_config_filename\x18\x06 \x02(\t:\x10\x63hip_config.json\x12\x1a\n\x0egenerator_seed\x18\x07 \x02(\x05:\x02\x32\x35\x12\x10\n\x08verboses\x18\x08 \x03(\x05\x12\x19\n\x11\x65xternal_core_ids\x18\t \x03(\x05\x12\x1c\n\x14\x65xternal_core_end_id\x18\r \x01(\x05\x12R\n\x0e\x63omputing_type\x18\n \x02(\x0e\x32(.neurosim.SimulationConfig.ComputingType:\x10SERIAL_COMPUTING\x12K\n\x0cnetwork_type\x18\x0b \x02(\x0e\x32&.neurosim.SimulationConfig.NetworkType:\rIDEAL_NETWORK\x12\x45\n\x0e\x63omputing_mode\x18\x0c \x01(\x0e\x32(.neurosim.SimulationConfig.ComputingMode:\x03SNN\x12\x1b\n\x0cverbose_comm\x18\x0e \x01(\x08:\x05\x66\x61lse\x12\x1b\n\rsource_filter\x18\x10 \x01(\t:\x04.csv\x12\x44\n\noutput_opt\x18\x11 \x01(\x0e\x32%.neurosim.SimulationConfig.OutputMode:\tfilenames\"Q\n\rComputingType\x12\x14\n\x10SERIAL_COMPUTING\x10\x00\x12\x16\n\x12PARALLEL_COMPUTING\x10\x01\x12\x12\n\x0eGPU0_COMPUTING\x10\x02\"2\n\x0bNetworkType\x12\x11\n\rIDEAL_NETWORK\x10\x00\x12\x10\n\x0cMESH_NETWORK\x10\x01\"!\n\rComputingMode\x12\x07\n\x03SNN\x10\x00\x12\x07\n\x03\x41NN\x10\x01\"$\n\nOutputMode\x12\r\n\tfilenames\x10\x00\x12\x07\n\x03\x62\x61r\x10\x01')
)



_SIMULATIONCONFIG_COMPUTINGTYPE = _descriptor.EnumDescriptor(
  name='ComputingType',
  full_name='neurosim.SimulationConfig.ComputingType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SERIAL_COMPUTING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PARALLEL_COMPUTING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GPU0_COMPUTING', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=713,
  serialized_end=794,
)
_sym_db.RegisterEnumDescriptor(_SIMULATIONCONFIG_COMPUTINGTYPE)

_SIMULATIONCONFIG_NETWORKTYPE = _descriptor.EnumDescriptor(
  name='NetworkType',
  full_name='neurosim.SimulationConfig.NetworkType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IDEAL_NETWORK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESH_NETWORK', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=796,
  serialized_end=846,
)
_sym_db.RegisterEnumDescriptor(_SIMULATIONCONFIG_NETWORKTYPE)

_SIMULATIONCONFIG_COMPUTINGMODE = _descriptor.EnumDescriptor(
  name='ComputingMode',
  full_name='neurosim.SimulationConfig.ComputingMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SNN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANN', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=848,
  serialized_end=881,
)
_sym_db.RegisterEnumDescriptor(_SIMULATIONCONFIG_COMPUTINGMODE)

_SIMULATIONCONFIG_OUTPUTMODE = _descriptor.EnumDescriptor(
  name='OutputMode',
  full_name='neurosim.SimulationConfig.OutputMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='filenames', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bar', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=883,
  serialized_end=919,
)
_sym_db.RegisterEnumDescriptor(_SIMULATIONCONFIG_OUTPUTMODE)


_SIMULATIONCONFIG = _descriptor.Descriptor(
  name='SimulationConfig',
  full_name='neurosim.SimulationConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_total_secs', full_name='neurosim.SimulationConfig.num_total_secs', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frequency_in_core', full_name='neurosim.SimulationConfig.frequency_in_core', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=200,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frequency_in_comm', full_name='neurosim.SimulationConfig.frequency_in_comm', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=20000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spike_sources', full_name='neurosim.SimulationConfig.spike_sources', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bitstream_filename', full_name='neurosim.SimulationConfig.bitstream_filename', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chip_config_filename', full_name='neurosim.SimulationConfig.chip_config_filename', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("chip_config.json").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='generator_seed', full_name='neurosim.SimulationConfig.generator_seed', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=25,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='verboses', full_name='neurosim.SimulationConfig.verboses', index=7,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='external_core_ids', full_name='neurosim.SimulationConfig.external_core_ids', index=8,
      number=9, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='external_core_end_id', full_name='neurosim.SimulationConfig.external_core_end_id', index=9,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='computing_type', full_name='neurosim.SimulationConfig.computing_type', index=10,
      number=10, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='network_type', full_name='neurosim.SimulationConfig.network_type', index=11,
      number=11, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='computing_mode', full_name='neurosim.SimulationConfig.computing_mode', index=12,
      number=12, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='verbose_comm', full_name='neurosim.SimulationConfig.verbose_comm', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source_filter', full_name='neurosim.SimulationConfig.source_filter', index=14,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b(".csv").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_opt', full_name='neurosim.SimulationConfig.output_opt', index=15,
      number=17, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SIMULATIONCONFIG_COMPUTINGTYPE,
    _SIMULATIONCONFIG_NETWORKTYPE,
    _SIMULATIONCONFIG_COMPUTINGMODE,
    _SIMULATIONCONFIG_OUTPUTMODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=919,
)

_SIMULATIONCONFIG.fields_by_name['computing_type'].enum_type = _SIMULATIONCONFIG_COMPUTINGTYPE
_SIMULATIONCONFIG.fields_by_name['network_type'].enum_type = _SIMULATIONCONFIG_NETWORKTYPE
_SIMULATIONCONFIG.fields_by_name['computing_mode'].enum_type = _SIMULATIONCONFIG_COMPUTINGMODE
_SIMULATIONCONFIG.fields_by_name['output_opt'].enum_type = _SIMULATIONCONFIG_OUTPUTMODE
_SIMULATIONCONFIG_COMPUTINGTYPE.containing_type = _SIMULATIONCONFIG
_SIMULATIONCONFIG_NETWORKTYPE.containing_type = _SIMULATIONCONFIG
_SIMULATIONCONFIG_COMPUTINGMODE.containing_type = _SIMULATIONCONFIG
_SIMULATIONCONFIG_OUTPUTMODE.containing_type = _SIMULATIONCONFIG
DESCRIPTOR.message_types_by_name['SimulationConfig'] = _SIMULATIONCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimulationConfig = _reflection.GeneratedProtocolMessageType('SimulationConfig', (_message.Message,), dict(
  DESCRIPTOR = _SIMULATIONCONFIG,
  __module__ = 'simulation_config_pb2'
  # @@protoc_insertion_point(class_scope:neurosim.SimulationConfig)
  ))
_sym_db.RegisterMessage(SimulationConfig)


# @@protoc_insertion_point(module_scope)
